from pydantic import BaseModel, Field
from typing import List


class ObjectLayoutSchema(BaseModel):
    object_name: str = Field(
        description="Unique name of the object in the work-cell."
    )
    object_type: str = Field(
        description="Type/category of the object, e.g. robot_base, table, workstation, task_object, target_area, obstacle."
    )
    position: List[float] = Field(
        description="3D position of the object center in meters: [x, y, z]."
    )
    orientation: List[float] = Field(
        description="Object orientation in roll-pitch-yaw Euler angles in radians: [roll, pitch, yaw]."
    )
    dimensions: List[float] = Field(
        description="Object bounding-box dimensions in meters: [length, width, height]."
    )
    role: str = Field(
        description="Functional role of the object in the task."
    )


class LayoutStrategySchema(BaseModel):
    layout_name: str = Field(
        description="Short name of the proposed work-cell layout."
    )
    layout_description: str = Field(
        description="Explanation of the layout design idea."
    )
    objects: List[ObjectLayoutSchema] = Field(
        description="List of all objects placed in the work-cell."
    )
    spatial_relations: List[str] = Field(
        description="Relevant spatial relations between objects."
    )
    constraints: List[str] = Field(
        description="Physical, geometric, and task-driven constraints considered in the layout."
    )
    expected_advantages: str = Field(
        description="Expected benefits of the layout with respect to feasibility, reachability, compactness, or task execution."
    )


class LayoutResponseSchema(BaseModel):
    scene_analysis: str = Field(
        description="Analysis of the scene, objects, spatial structure, and relevant geometry."
    )
    task_analysis: str = Field(
        description="Analysis of the task requirements and layout constraints."
    )
    layout_strategies: List[LayoutStrategySchema] = Field(
        description="Candidate work-cell layout strategies generated by the VLM."
    )